title: The Code 
author: Alv
email: Alvandsaket@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You dont know me because im new here!

# social links
twitter_username: Alvand Saket # DO NOT include the @ character, or else the build will fail!
github_username:  Alvandsk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
